db.url=jdbc:postgresql://SERVIDOR:PUERTO/NOMBRE_BD
db.username=USUARIO
db.password=PASSWORD
db.driver=org.postgresql.Driver

hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=none