package mx.org.inegi.sistemacaptura.config;

/** Generated by Maven. Select -Ppruebas or -Pproduccion; do not edit generated files. */
public final class DatabaseTables {
    private DatabaseTables() {}
    public static final String AMBIENTE = "${deployment.environment}";
    public static final String SELECCION = "${tables.seleccion.schema}";
    public static final String ARMONIZACION = "${tables.armonizacion.schema}";
    public static final String TICKETS_SCHEMA = "${tables.tickets.schema}";
    public static final String CLASIFICACIONES_A = "clasificaciones${tables.armonizacion.suffix}";
    public static final String CLASIFICACIONES_A_SQL = ARMONIZACION + "." + CLASIFICACIONES_A;
    public static final String CLASIFICADORES_A = "clasificadores${tables.armonizacion.suffix}";
    public static final String CLASIFICADORES_A_SQL = ARMONIZACION + "." + CLASIFICADORES_A;
    public static final String COMENTARIOS_PP_A = "comentarios_pp${tables.armonizacion.suffix}";
    public static final String COMENTARIOS_PP_A_SQL = ARMONIZACION + "." + COMENTARIOS_PP_A;
    public static final String DATOS_ABIERTOS_A = "datos_abiertos${tables.armonizacion.suffix}";
    public static final String DATOS_ABIERTOS_A_SQL = ARMONIZACION + "." + DATOS_ABIERTOS_A;
    public static final String DESAGREGACION_A = "desagregacion${tables.armonizacion.suffix}";
    public static final String DESAGREGACION_A_SQL = ARMONIZACION + "." + DESAGREGACION_A;
    public static final String DESGLOSE_A = "desglose${tables.armonizacion.suffix}";
    public static final String DESGLOSE_A_SQL = ARMONIZACION + "." + DESGLOSE_A;
    public static final String FUENTES_A = "fuentes${tables.armonizacion.suffix}";
    public static final String FUENTES_A_SQL = ARMONIZACION + "." + FUENTES_A;
    public static final String MDEA_A = "mdea${tables.armonizacion.suffix}";
    public static final String MDEA_A_SQL = ARMONIZACION + "." + MDEA_A;
    public static final String MICRODATOS_A = "microdatos${tables.armonizacion.suffix}";
    public static final String MICRODATOS_A_SQL = ARMONIZACION + "." + MICRODATOS_A;
    public static final String ODS_A = "ods${tables.armonizacion.suffix}";
    public static final String ODS_A_SQL = ARMONIZACION + "." + ODS_A;
    public static final String PERTINENCIA_A = "pertinencia${tables.armonizacion.suffix}";
    public static final String PERTINENCIA_A_SQL = ARMONIZACION + "." + PERTINENCIA_A;
    public static final String PROCESOS_A = "procesos${tables.armonizacion.suffix}";
    public static final String PROCESOS_A_SQL = ARMONIZACION + "." + PROCESOS_A;
    public static final String TABULADOS_A = "tabulados${tables.armonizacion.suffix}";
    public static final String TABULADOS_A_SQL = ARMONIZACION + "." + TABULADOS_A;
    public static final String TICKETS_A = "${tables.tickets.name}";
    public static final String TICKETS_A_SQL = TICKETS_SCHEMA + "." + TICKETS_A;
    public static final String VARIABLES_A = "variables${tables.armonizacion.suffix}";
    public static final String VARIABLES_A_SQL = ARMONIZACION + "." + VARIABLES_A;
    public static final String VARIABLES_TABULADOS_A = "variables_tabulados${tables.armonizacion.suffix}";
    public static final String VARIABLES_TABULADOS_A_SQL = ARMONIZACION + "." + VARIABLES_TABULADOS_A;
    public static final String COMENTARIOS_PP_S = "comentarios_pp${tables.seleccion.suffix}";
    public static final String COMENTARIOS_PP_S_SQL = SELECCION + "." + COMENTARIOS_PP_S;
    public static final String FUENTES_S = "fuentes${tables.seleccion.suffix}";
    public static final String FUENTES_S_SQL = SELECCION + "." + FUENTES_S;
    public static final String MDEA_S = "mdea${tables.seleccion.suffix}";
    public static final String MDEA_S_SQL = SELECCION + "." + MDEA_S;
    public static final String ODS_S = "ods${tables.seleccion.suffix}";
    public static final String ODS_S_SQL = SELECCION + "." + ODS_S;
    public static final String PERTINENCIA_S = "pertinencia${tables.seleccion.suffix}";
    public static final String PERTINENCIA_S_SQL = SELECCION + "." + PERTINENCIA_S;
    public static final String PROCESOS_S = "procesos${tables.seleccion.suffix}";
    public static final String PROCESOS_S_SQL = SELECCION + "." + PROCESOS_S;
    public static final String VARIABLES_S = "variables${tables.seleccion.suffix}";
    public static final String VARIABLES_S_SQL = SELECCION + "." + VARIABLES_S;
}
